this.setUniform('float', 'time', performance.now() / 1000)
this.setUniform('float','pixSize', 1 / width)
this.setUniform('float','width', width)
this.setUniform('float','height', height)
this.setUniform('float','aspRatio', width/height)
this.setUniform('vec2','mouse', mouse)
this.setUniform('float','pi', Math.PI)
this.setUniform('float','camAspRatio', $video.videoWidth/$video.videoHeight)